package:
  name: giropops-senhas
  version: 1.0.0
  description: giropops-senhas with melange
  epoch: 0
  target-architecture:
    - all
  copyright:
    - license: GNU General Public License
  dependencies:
    runtime:
      - python3

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - gcc
      - musl-dev
      - python3
      - python3-dev
      - py3-pip
      - py3-virtualenv
  
pipeline:
  - name: Build giropops-senhas application
    runs: |
      WEB_APP_DIR="${{targets.destdir}}/giropops-senhas"
      mkdir -p "${WEB_APP_DIR}"
      cp app.py "${WEB_APP_DIR}/app.py"
      cp -R static "${WEB_APP_DIR}/static"
      cp -R templates "${WEB_APP_DIR}/templates"
      cp tailwind.config.js "${WEB_APP_DIR}/tailwind.config.js"
      virtualenv "${WEB_APP_DIR}/venv"
      sh -c "source '${WEB_APP_DIR}/venv/bin/activate' && pip install -r requirements.txt"
